version: "3"

services:
  cake_web:
    container_name: cake_web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cake_db
    ports:
      - "80:80"
    volumes:
      - "./app:/var/www/html"

  cake_db:
    container_name: cake_db
    image: mysql:8.0
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: cake_cms
      MYSQL_USER: pass-user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  cake_test_db:
    container_name: cake_test_db
    image: mysql:8.0
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: cake_cms
      MYSQL_USER: pass-user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root